spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/excel_helper?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  application:
    admin:
      enabled: true
    name: excel-helper
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  charset:
    console: UTF-8

